### ISSUE TITLE
Buggy sound on "Dragon Ninja" & "Batman the Movie"

### ISSUE THREAD

**Issue by FloLore** [ColinPitrat/caprice32#104]
Hi,
It lacks some sounds in these games, sound effects in particular ... I tested on various versions (original and crack) and the result is the same. Tested with the latest version (4.4.0). Is the problem coming from the emulator or an option I missed?

**Comment by ColinPitrat** [comment]
You have sounds but not all of them ? If so it's probably the emulator. You can double check if it helps setting 128kB of RAM (both games behave slightly different when more memory is available). You can also check with 6128+ model.

I'll try to have a look at it soon. Is the issue obvious when you play or do you have to know the game to know that something is missing ?

**Comment by FloLore** [comment]
Hi ColinPitrat, for the "Batman the movie" game, only the sound effects are missing, the music works. For Dragon Ninja, there is no music (it's normal) but there are no sound effects, except some strange sounds ... I tested them on my amstrad in comparison to be sure. I tested with more memory than 128k, also uncheck the emulation speed limitation, the problem persists... Other worries, the protection "Speedlock D7" used by "Ocean" for these games Batman, RoboCop and Dragon Ninja is not recognized by the emulator, if you could correct that, would be great?

**Comment by FloLore** [comment]
I just tested the protection on caprice32 3.6.1, and the games (original version) works very well such as Batman, Dragon Ninja, RoboCop, Extreme ... The sound effects also pass very well on the 3.6.1 version. If that can help you fix the problem?

**Comment by ColinPitrat** [comment]
Yes, knowing this should be very helpful. I just have to bisect releases until I find where the issue was introduced.

**Comment by ColinPitrat** [comment]
And here it is (for the record, I'll look deeper into it later):
4ca62354d884b744b801921d195f21863bbcae47 is the first bad commit
commit 4ca62354d884b744b801921d195f21863bbcae47
Author: Colin Pitrat <colin.pitrat@gmail.com>
Date:   Sat Jan 9 01:41:35 2016 +0100

    Add out of the box support for Mulitface II

:100644 100644 1fb27ea46bdaa3d134ef6d1669cd27fa2e5ebebc bc7c01d2eebae74cf8f1a340284eb094d0cdcf6d M	cap32.cfg
:100644 100644 b165116176a0ecf70cde0625d583dab5ea03a43f 7db3d4866d1b79e595f65836d1fb06b55b1f56b8 M	cap32.cpp
:040000 040000 732d0891a142ba6c66e52c5f0b1e779a2d18887d 435dc7f86ec4f2e8924a2ce551f2b064866c0c07 M	gui
:040000 040000 0b283e44dd368a743187bfc4b1c7987788a9fb98 30e848be9726a91d1adb1e2140a2922ca74b66b5 M	rom

**Comment by ColinPitrat** [comment]
Indeed, activating the MF2 by default was a bad idea.
You can fix it by setting the following in your configuration file:
`mf2=0`

I just sent a patch to fix this in the default configuration.

**Comment by ColinPitrat** [comment]
Note: I need to do the same for the sound issue.

**Comment by ColinPitrat** [comment]
And for the sound this seems to come from ebdf4b9b70b8523a5ea53296a5b487d976394e99

**Comment by FloLore** [comment]
Excellent! "Ocean" games with "Speedlock D7" protection work again. Thank you for finding the problem for that. For the buggy sound, it will be good that you can correct it.

**Comment by sebhz** [comment]
I remember trying to "optimize" the original code like you a long time ago (before I started contributing to thi fork) and finally giving up because no matter how hard I tried eventhough the code compiled fine and looked perfectly ok to me, the sound emulation was always strange !Ulrich was a wizard... my only explanation :-)


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Colin Pitrat <notifications@github.com> 
Date : 10/12/2017  18:58  (GMT+01:00) 
À : ColinPitrat/caprice32 <caprice32@noreply.github.com> 
Cc : Subscribed <subscribed@noreply.github.com> 
Objet : Re: [ColinPitrat/caprice32] Buggy sound on "Dragon Ninja" &amp; "Batman
&nbsp; the Movie" (#104) 

And for the sound this seems to come from ebdf4b9

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ColinPitrat/caprice32","title":"ColinPitrat/caprice32","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ColinPitrat/caprice32"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ColinPitrat in #104: And for the sound this seems to come from ebdf4b9b70b8523a5ea53296a5b487d976394e99"}],"action":{"name":"View Issue","url":"https://github.com/ColinPitrat/caprice32/issues/104#issuecomment-350566088"}}}

**Comment by ColinPitrat** [comment]
The sound issue was an alignment problem in a struct. This should now be fixed (bullets sounds in batman are back).
Please reopen if there are still some issues.
