### ISSUE TITLE
Software scaling video drivers seem to have vsync issues

### ISSUE THREAD

**Issue by FloLore** [ColinPitrat/caprice32#106]
Hi,
Would not it be possible to have vertical synchronization? Because on some titles with vertical scrolling, the graphics are broken. Maybe with a resolution of the desktop, natively for the screen and for the graphics drivers, the v-synch of the graphics driver could be enough?
Currently, we can put a resolution of our choice, but it does not stretch to the entire screen, and none of the settings of v-synch on the graphics drivers under Windows (nvidia in my case) do not work ...

**Comment by ColinPitrat** [comment]
I'm not sure what you mean exactly. The vsync of caprice should be handled by SDL. The vsync of the game running in the emulator should be the same as when running in a CPC (if not it's a bug on caprice side, for example in interruptions emulation). 
Do you have a concrete example ?

**Comment by FloLore** [comment]
After some tests, it seems that it is perfect in simple graphics rendering modes like: "Double size with hardware flip" but not in the rendered graphic rendering modes like "supereagle or scale2x". In scale2x for example, the display area always corresponds to a resolution of 800x600 in a fullscreen of 1920x1080. Moreover on some titles like "Anarchy", a scan of the screen is done regularly, that is to say: a vertical line which breaks the graphic like a defect of vertical synchronization. I will take a screenshot and try to send it to you.

**Comment by FloLore** [comment]
Here is an example, I use the supereagle mode in 1920x1080.

https://image.noelshack.com/fichiers/2017/50/7/1513515934-desktop-screenshot-2017-12-17-14-03-16-16.jpg

Sorry for my English, I do not speak it very well ...

**Comment by FloLore** [comment]
In fact, the problem of fullscreen in filter mode like scale2x or supereagle, concerns all the resolutions above the 800/600, which is in 4/3, 16/9 and 16/10.

**Comment by ColinPitrat** [comment]
Both supereagle and scale2x double the resolution of the CPC screen of the CPC, i.e 768x540.
In full screen mode, the resolution of the screen is switched to what is configured in cap32.cfg, by default:
```
scr_width=800
scr_height=600
scr_bpp=32
```
The emulator works with a 768x540 in the whole code no matter the resolution. From your description of the problem (only happens when resolution > 800x600), I think the issue can only come from the flip methods. They are indeed slightly different for the following plugin that do pixel-level manipulations:
 - Super eagle 
 - Scale2x
 - Advanced Scale2x
 - TV 2x
 - Software bilinear
 - Software bicubic
 - Dot matrix

For those video drivers, the flip method actually does the computation directly on the video surface, optionally locking it and calling SDL_UpdateRects after that. I wonder if it could be that locking the surface doesn't actually guarantee that the modifications won't affect the display. It could be easily tested by introducing a third surface and blitting it.

**Comment by CodyMast** [comment]
If the code had allowed the display of filters in various resolutions as on other emulators, this problem would be no more ... I see that a lot of CPC emulators use the 800x600 display, it's pity...

**Comment by ColinPitrat** [comment]
@CodyMast I'm not sure what you mean.
These algorithm are for scaling up the resolution with smoothing (to "enhance" the low resolution images). They only support doubling the resolution, which is why they always work with 768x540. Then the result can be embedded in any higher screen resolution with black bands around.

**Comment by ColinPitrat** [comment]
I had a look today. I manage to reproduce the issue on my computer not only in all video modes except hardware flip, whether in fullscreen or not.
Thinking about it, it seems that hardware flip should be an option, available for all plugins, rather than a distinct video plugin.

**Comment by ColinPitrat** [comment]
Actually from SDL documentation:
SDL_DOUBLEBUF:	Enable hardware double buffering; only valid with SDL_HWSURFACE. Calling SDL_Flip will flip the buffers and update the screen. All drawing will take place on the surface that is not displayed at the moment. **If double buffering could not be enabled then SDL_Flip will just perform a SDL_UpdateRect on the entire screen.**

So AFAIU, it's safe to always pass SDL_DOUBLEBUF and to always use SDL_Flip. Worst case is a performance degradation in full screen because UpdateRect will be called on the whole screen instead of only the CPC screen.

**Comment by ColinPitrat** [comment]
I tried using SDL_DOUBLEBUF and SDL_Flip for other video driver but this didn't remove the glitches.
At this point, I'm puzzled on what could be the source of this issue !

**Comment by ColinPitrat** [comment]
Tried a bisect just in case, this issue has always been there.
Thinking more about it, this is not a vsync issue of the emulator. A vsync issue would show tearing of the image when it changes. Here we can observe glitches in static screens like the 'skip frame one' screen, or in static part of the screen (border).
It looks like an issue in the emulation of the hsync of the CPC. Yet it depends on the video driver used which is very disturbing ...

**Comment by ColinPitrat** [comment]
The issue becomes clearer.
It is in fact due to 16bits color. That's why hardware mode is immune to it, it will always be in 32 bpp on my computer. In software 'Half/Double size', the issue disappear when selecting 32 bpp. When selecting 24 bpp, the artefact is not a shifted line but a line with color shifted. In 16 bpp the line is shifted by one pixel whereas in 8 bpp the line is shifted by two pixel.

**Comment by ColinPitrat** [comment]
So in the end, the issue was that the SDL surfaces are addressed as dword arrays.
When the emulation loop interrupts on a pixel index that is not a multiple of 4, this leads to a rounding.
Fixed this by addressing SDL surfaces as bytes arrays.

I also modified video drivers that require 16bpp mode so that they transparently switch to it instead of giving an error.
