### ISSUE TITLE
caprice32 - debian 8 - Segmentation Fault

### ISSUE THREAD

**Issue by bert003** [ColinPitrat/caprice32#14]
When pressing F1 to adjust any settings and pressing Save, caprice32 exits with Segmentation Fault  and settings are not saved.

Logs:

segfault at 816b000 ip 080f278f sp bfe97d0c  error 4
segfault at 816b000 ip 080f278f sp bfe25f5c  error 4

**Comment by ColinPitrat** [comment]
Could you try to get information from the core ?

The best way for this is to build using `make debug` instead of just `make` (if you already built, you'll need to do `make clean` before so that everything is rebuilt). 

Then, if gdb is available, reproduce the core in gdb with `gdb ./caprice32`. Once the program stops (the CPC window may still be visible but gdb will show its prompt again) type `bt`. This will give you the backtrace of the core.

If you don't have gdb and don't want to install it, reproduce the core normally and send me the core file. You may need, for this, to run `ulimit -c unlimited` before launching caprice. Then when the core occurs, you should have a file `core` or `core.XXXXX` (where XXXXX will be a number) in the current directory.

Thanks for reporting bugs !

**Comment by bert003** [comment]
Ok so...

make debug resulted in 57 tests passed successfully.

However, when I executed gdb ./cap32, the emulator does not load and I am stuck in gdb prompt saying Reading symbols from ../cap32

Kindly advise...

**Comment by ColinPitrat** [comment]
Sorry, I forgot to precise to press `r` once in gdb.
However, you may not need to worry: I managed to reproduce the issue.

**Comment by ColinPitrat** [comment]
I fixed it, sorry for the inconvenience.
Please confirm this solves your issue.

**Comment by bert003** [comment]
Issue solved successfully. Thanks for your immediate action.
