### ISSUE TITLE
Possible F1 Menu Update

### ISSUE THREAD

**Issue by bert003** [ColinPitrat/caprice32#31]
It is a minor issue but, for example, while I was in the Input tab with the joystick emulation option ticked and I pressed F7, the checkbox remained ticked but the emulation was disabled as it should.

My point is: Can the menu options be updated in real time so that, for example, in the above scenario the checkbox ticks and unticks if the menu is open?

The system works though. In fact if I close the menu and open it again, the checkbox is unticked then.

Hope I am not asking too much but I am putting myself in the shoes of a noob...

**Comment by ColinPitrat** [comment]
Amazing, I would have expected F7 to not work while in the menu ... I'll have a look.

**Comment by ColinPitrat** [comment]
I confirm pressing F7 while in the menu has no effect (joystick emulation is not toggled).
Making it work would be a bit tricky as the handling of events is completely separated between the emulator and the GUI.
Are you OK to close this one ?

For joystick emulation, an OSD message would be nice so that user have some feedback it's being toggled. I open a separate issue for this.

**Comment by bert003** [comment]
Yes perfectly agree.

There should be some sort of notification message and in the documentation there should be written that shortcuts do not work while the menu is visible on screen.
