### ISSUE TITLE
Poor performances

### ISSUE THREAD

**Issue by ColinPitrat** [ColinPitrat/caprice32#54]
From issue 39:
Hello! First of all thanks a lot for this fine emulator! The CPC Schneider was the very first computer (& gaming device) I had as a kid and seeing that green screen and hearing the Nemesis soundtrack today brings back warm memories ^_^

I'm very sorry I'm writing this here because it doesn't really belong here... though maybe it kinda does because I could really not find any place on the net where there was discussion about this emulator (apart from very outdated ones); there doesn't seem to any forum or discord or any other place to ask questions.

What I wanted to ask is if it's normal that I'm only getting around 17 FPS (34%), even when not running a game. Disabling sound seems to double that but nothing else brings emulation to 100%. Maybe there's some kind of setting I missed or something? (My PC is quite strong).
I actually used Caprice32 one or two years ago and I think I remember that I didn't have any speed issues back then. Now that I found more of my old games I'd love to play them but yeah, the speed kinda kills the fun.
Sorry again for posting this here, thanks a lot and it would be great if you could help me a little here :)

**Comment by ColinPitrat** [comment]
Hello,

Not managing to reach 100% on a modern computer is not normal. On my laptop, when I uncap the speed, I easily reach more than 1000% (10x). Even on my 10 years old netbook I reach 100% without drops. The ~35% is about what I get on a first generation raspberry pi.

What kind of hardware do you use (CPU, graphic card) ? Do you run it under Linux ? Do you know which SDL video driver you're using ? Do you run some games using SDL (ideally 1.2) with good performances ?

One thing you can try is changing the video plugin. This can be done either from the GUI (press "F1" - "Options" button - "Video" tab - "Video plugin" dropdown list) or by changing `scr_style` in cap32.cfg.

You can try 'Half-size with hardware flip' (scr_style=0) which should be the fastest (but screen will be small). You can also try 'Half-size' (scr_style=2) and see if it's better or not. Finally, try also 'OpenGL scaling' (scr_style=11).

Finally, you can build caprice32 with profiling activated:
`make CUSTOM_CFLAGS=-pg LDFLAGS=-pg DEBUG=1`
`./cap32`

Run the emulator for a few dozen of seconds at least. Then:
`gprof ./cap32 gmon.out > profile.txt`

And attach `profile.txt` to this issue.

Thanks

**Comment by StripTheSoulwhostolemydamnname** [comment]
Alright, thanks! 
These are my PC specs: Intel i5-4690k (Devil's Canyon) @ 3.5 GHz (+Scythe Mugen) / Gainward GTX 1070 Phoenix (OC'd) / ASUS Z97 PRO GAMER / 16GB G.Skill DDR3-2400 CL10 TridentX / X-Fi XtremeMusic / Win10 Pro 64bit; so NOT Linux.

I'm using lots of other emulators and there's SDL stuff all over the place but I don't know exactly what that means or what version it is (or where to see that).

Unfortunately, nothing happens when I press F1. 
Anyway, now I'm actually quite confused. It seems the zip file which I downloaded here didn't even contain an .exe file...? So I'm not sure what I'm actually using right now (yeah, I know, I shouldn't have just thrown it into the old folder) is a mix of a years old build (with a caprice32.exe which actually has a toolbar on top), a build from here ( https://sourceforge.net/projects/caprice32/ not sure if that's the same as yours, just older; it has this cap32.exe file which actually works at 100% speed it seems, but doesn't have a toolbar and pressing F1 just gets it into full screen at 0 FPS) and well, the files from the zip I got right here.
Not sure how to use the files from the zip alone, though. Or does that stuff still need to be compiled?
Unfortunately, I have no idea about compiling and stuff.
I guess, I could use that build from the link above and configure it without the toolbar, using the cap32.cfg?

**Comment by ColinPitrat** [comment]
OK so you're probably using a very old build (~2004) coming from sourceforge or somewhere else.
I'll see if I can make a release including an exe for windows any time soon.

**Comment by StripTheSoulwhostolemydamnname** [comment]
The on from the link seems to be from last fall, though, right? 
Anyway, would be great if you could make a recent windows build soon (even on EmuCR the last one seems to be from 2011).
Cheers!

**Comment by ColinPitrat** [comment]
The date on sourceforge is probably referring to the last comment asking if the project is dead :-) The build itself is 13 years old !

I built a new version for windows:
http://the3fold.free.fr/divers/cap32.zip

I gave it a quick try and it seems there are a few issues with it (I had some bugs with the sound). You can still give it a try though and tell me what it gives for performances (and also if you experience sound issues or not).

**Comment by StripTheSoulwhostolemydamnname** [comment]
Whoops, 13 years, ouch! ^_^
Thanks for the build! Unfortunately, it doesn't work for me, yet. When executing the cap32.exe, the program crashes with this error:
"terminate called after throwing an instance of 'std::logic_error'
   what(): basic_string::_M_construct null not valid

This application has requested the Runtime to terminate it in an unusual way. 
Please contact the application's support team for more information."

I'll try to update my runtimes, but they should be more or less up-to-date. Maybe some setting I should change in the cap32.cfg before executing?

**Comment by ColinPitrat** [comment]
Interesting, I had the same error when trying to run on wine but it was working fine on the Windows 7 laptop on which I had the opportunity to test. I'll try to understand where this comes from.

**Comment by melindmi** [comment]
This is not a trivial issue. I'll have to work more on that.
In your case, you may want to try WinAPE. This is by far the best CPC emulator on Windows: http://www.winape.net

**Comment by ColinPitrat** [comment]
This is not a trivial issue. I'll have to work more on this.
On your side, you may want to have a look at WinAPE. This is by far the best CPC emulator on Windows:
http://www.winape.net

**Comment by ColinPitrat** [comment]
This is a duplicate of issue #11

**Comment by StripTheSoulwhostolemydamnname** [comment]
Alright, thanks a lot either way :)

**Comment by ColinPitrat** [comment]
If you have the opportunity, you can give another try to http://the3fold.free.fr/divers/cap32.zip
It's a 64bits build. I'm not very optimistic but this may work :-)

**Comment by StripTheSoulwhostolemydamnname** [comment]
Yeah, it's got the same issue :)

**Comment by sebhz** [comment]
For what it is worth... I did spend some time today to compile Caprice32 on a Windows 8 machine using MSYS2/mingw64. Once all the dependencies are installed compilation is pretty straightforward. cap32 runs fine with it - I tried two disks (sorcery and trailblazer), and I get 100 fps consistently. Audio seems correct. I'll try the same binary on my wife's laptop (Win10) tonight. If it works fine, I'll share it !

Note that there is one problem with this executable: trying to invoke the "Option" menu freezes the emulator completely. This is painful but you can still use the emulator by changing manually the settings in the .cfg file. I'll look into this.

**Comment by StripTheSoulwhostolemydamnname** [comment]
Haw, that surprises me... I have no idea about coding and stuff, but my PC is always up-to-date, clean, and got all kinds of dependencies stuff installed. I never have an emulator (or other kind of software) not working.

**Comment by ColinPitrat** [comment]
Don't worry, it has nothing to do with your computer !
It's an issue either with caprice itself or with the way we're building it for windows.

**Comment by ColinPitrat** [comment]
We found and fixed the issue.
You can try the new version:
 - 32 bits: http://the3fold.free.fr/divers/cap32-i686.zip
 - 64 bits: http://the3fold.free.fr/divers/cap32-x86_64.zip

Please tell me if performances are good or not.

**Comment by StripTheSoulwhostolemydamnname** [comment]
Yay, it works, and it works well! 100%
At least in the normal interface. I cannot say how it is for games because I'm not sure how to insert a disk without the menu bar. I found the settings via F1, but there's no option for inserting a disk. How do I do that? (I know how to load a game once the disk is inserted).

**Comment by ColinPitrat** [comment]
When pressing F1, you have a Load/Save button just below Options. In the
load/save menu select disk drive A in the drop down and then pick your .dsk
file

Regards,
Colin

**Comment by StripTheSoulwhostolemydamnname** [comment]
Ah, ok, I only saw the snapshot option before. And after I put the games into a 'disk' folder instead of 'rom' I could actually pick them ;)
However, I hit another block in the road. I need the " sign to load the game. But on neither the French nor the English keyboard could I find or produce that sign. On my German keyboard it's Shift+2.
Sorry for all that handholding >_<

**Comment by sebhz** [comment]
Use the virtual keyboard !

Shift-F1 to invoke it. Press the run " key on the right, close the virtual
keyboard, lo and behold, you got it !

Cheers !

Seb

> Le 17 mars 2017 à 16:21, StripTheSoulwhostolemydamnname

**Comment by StripTheSoulwhostolemydamnname** [comment]
Ah, yeah, that worked (at least in window mode) :)
Games are fine and running at full speed. Thanks a lot! :D
