### ISSUE TITLE
Slots handling needs to be redesigned

### ISSUE THREAD

**Issue by sebhz** [ColinPitrat/caprice32#56]
The way Caprice32 handles dsk/cpr and friends is... strange.
We seem to derive drvXXX_path from the arguments (if any), then reuse it. And the code is pretty redundant here - as indicated in the comments !
We could handle it more sensibly, the way other emulators do it:
- specify xxx_path in the configuration file ("the directories where disks / cartridge / tapes / whatever are stored") - drvA and drvB path would be the same and become "dsk_path" or something like this.
- keep the xxx_file in the configuration file, in case some people want to have some disk/cartridges installed by default.
- get rid of the xxxx_zip in the conf file (useful internally but no need to expose it as we can detect the extension).
- get rid of the xxxx_format in the conf file (mostly unused anyway)
- one can invoke 'cap32 toto.dsk' -> caprice32 will look for disk/toto.dsk and load it in the first free disk drive.
- optionally,  maybe, one can invoke 'cap32 /home/mycpr/truc.cpr. In this case we would detect a full path and try and load it as is, without using the xxxx_path (as the user made it clear he/she wants to load an alternate path). This would be nice to have only though... forcing the user to put all images in the same directory seems OK to me. This is the Mame way, isn't it ?

**Comment by ColinPitrat** [comment]
Indeed, I have it in my TODO list to clean this.

`drv[AB]_format` are indeed not used at all. Even `disk_format` and `dsk_format` are not used. It would only be useful to provide a formatting functionality to the user inside caprice32 and in such a case, having a format "attached" to the drive in the configuration doesn't make sense.

The only benefit I see from the `xxx_(path|file|zip)` is the ability to specify a given file in a zip that has multiple matching files. This is a small benefit and unpractical as it requires editing the config file !
On the other hand, it brings issues. When starting with a file passed on the command line, if you change something in Options and save, it will update the variables in the configuration file and therefore impact next runs.
Another issue: if you put a zip file it is put in the path variable and when you open the load/save dir, it fails (as it's not a dir). Initially there was no way to do anything. I "fixed" the bug by changing it to ~ but it's not perfect.
So I'm all for killing it ! My recent patch introducing `file_load` aimed at replacing all this at one point. The "annoying" part is the logic for the choice of the disk drive that is different in the GUI (we know where to load) and on the command line (A if free, otherwise B if free, otherwise ignore).

However, I'm not sure the 5th point (lookup file in another directory) is really needed. I was thinking of removing all the variables except the '_path' and to use those only for the Load/Save dialog. When giving arguments on the command line (or drag&dropping which is the same) it's easier anyway to provide the correct path.

**Comment by sebhz** [comment]
Fine. So we remove all the variables except xxx_path, use them for the load/save dialog. Command line arguments always specify the full and correct path. I'll look into this :-)

**Comment by sebhz** [comment]
What about rom/system.cpr cartridge ?

**Comment by sebhz** [comment]
Never mind... it seems this is actually hardcoded in cap32.cpp and system.cpr is used anyway.

**Comment by ColinPitrat** [comment]
Yes, it should be considered the same way as ROMs for non Plus models that are also hardcoded.

**Comment by ColinPitrat** [comment]
Considering this as implemented. Thanks !
